DROP TABLE IF EXISTS LOGIN_ID_MASTER_TABLE;
CREATE TABLE `LOGIN_ID_MASTER_TABLE` (
  `No` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(3) NOT NULL,
  `passward` varchar(3) NOT NULL,
  `latest_login_data` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_person` varchar(30) NOT NULL DEFAULT 'system',
  PRIMARY KEY (`No`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;